apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "magento.fullname" . }}-cron
  labels:
    app.kubernetes.io/name: {{ template "magento.fullname" . }}
    app.kubernetes.io/component: php
    helm.sh/chart: {{ template "magento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"  
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ template "magento.fullname" . }}
            app.kubernetes.io/component: php
            helm.sh/chart: {{ template "magento.chart" . }}
            app.kubernetes.io/instance: "{{ .Release.Name }}"
            app.kubernetes.io/managed-by: "{{ .Release.Service }}"  
        spec:
          restartPolicy: Never
          containers:
          - name: {{ template "magento.fullname" . }}-cron
            image: {{ .Values.php.image | quote }}
            command: ["/bin/sh"]
            args:
            - -c
            - |
              php bin/magento cron:run
            env:
            {{- range $key, $val := .Values.php.env }}
              - name: {{ $key }}
                value: {{ $val | quote }}
            {{- end }}       
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  failedJobsHistoryLimit: 20
  successfulJobsHistoryLimit: 5