apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magento.fullname" . }}-nginx-config
  labels:
    app.kubernetes.io/name: {{ template "magento.fullname" . }}
    helm.sh/chart: {{ template "magento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "files/nginx/*.conf").AsConfig | indent 2 }}