apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magento.fullname" . }}-nginx-config
  labels:
    app.kubernetes.io/name: {{ template "magento.fullname" . }}
    helm.sh/chart: {{ template "magento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  default.conf: |
    resolver kube-dns.kube-system.svc.cluster.local valid=5s;
  
    upstream fastcgi_backend {
      server  {{ include "magento.fullname" . }}-php:9000;
    }
  
    server {
      listen 80;
      server_name _;
      set $MAGE_ROOT /var/www/html;
      include /var/www/html/magento2.conf;
    }
{{ (.Files.Glob "files/nginx/*.conf").AsConfig | indent 2 }}