apiVersion: v1
kind: Service
metadata:
  name: {{ template "magento.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ template "magento.fullname" . }}
    app.kubernetes.io/component: nginx
    helm.sh/chart: {{ template "magento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "magento.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ template "magento.fullname" . }}
    helm.sh/chart: {{ template "magento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: nginx
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "magento.fullname" . }}
        app.kubernetes.io/component: nginx
        helm.sh/chart: {{ template "magento.chart" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    spec:
      containers:
      - image: {{ .Values.nginx.image | quote }}
        imagePullPolicy: Always
        name: {{ template "magento.fullname" . }}-web
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: default.conf
        - mountPath: /var/www/html/magento2.conf
          name: nginx-config
          subPath: magento2.conf
        - name: media
          mountPath: /var/www/html/pub/media
        - name: static
          mountPath: /var/www/html/pub/static
          
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ template "magento.fullname" . }}-nginx-config
        name: nginx-config
      - name: media
        persistentVolumeClaim:
          claimName: {{ template "magento.fullname" . }}-media
      - name: static
        persistentVolumeClaim:
          claimName: {{ template "magento.fullname" . }}-static